name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution-type: 'adopt'

    - name: Build Java Game
      run: |
        # Assuming your game's entry point is Main.java and the package is com.example.game
        javac -source 1.8 -target 1.8 src/com/vulps/main/*.java

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install Butler
      run: |
        # -L follows redirects
        # -O specifies output name
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        # GNU unzip tends to not set the executable bit even though it's set in the .zip
        chmod +x butler
        # just a sanity check run (and also helpful in case you're sharing CI logs)
        ./butler -V

   # - name: Create Patch and Push
   #   run: |
 #       butler patch build username/game:channel
#
