name: CodeKeepers Review Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: CodeKeepers Review Request Action
        uses: Vulps22/announce-code-review@v1.1.0
        with:
          api_token: ${{ secrets.CK_API_SECRET }}
